version: "3"

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
    ports:
      - 8080:80
    networks:
      - mynetwork

  mysql:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork
    environment:
      - MYSQL_DATABASE=new_db
      - MYSQL_USER=dev_db
      - MYSQL_PASSWORD=your_password
      - MYSQL_ROOT_PASSWORD=your_root_password

volumes:
  mysql-data:

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/28
